In [1]:
import numpy as np

In [2]:
my_array = np.array([[1,2,3,4,5,6] , [1,2,3,4,5,6]])
print(my_array)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [3]:
my_array[1,5] # to get a specific element from the array you can also give negative value like -1

6

In [4]:
my_array[0 , :] # get a specific rows : means all

array([1, 2, 3, 4, 5, 6])

In [5]:
my_array[: , -2] # to get a specifc column

array([5, 5])

In [6]:
my_array[0 , 1 : 6 : 1]  # statrt , end (this is exclusive) , step size

array([2, 3, 4, 5, 6])

In [7]:
# if you want to change elements in the matrix then you can do it like this
my_array[1,4] = 99
# print(my_array)
#  if you wanna change something like a column then you can specify it like this
my_array[ : ,2] = [0,0]
print(my_array)

[[ 1  2  0  4  5  6]
 [ 1  2  0  4 99  6]]


In [8]:
# 3 dimensional array
b = np.array([[[1,2,3,4,5,6], [1,2,3,4,5,6] , [1,2,3,4,5,6]]])
print(b)

[[[1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]]]


In [9]:
b.reshape()

TypeError: ignored