In [ ]:
import numpy as np

In [ ]:
# creating array filled with zeros

In [ ]:
zero_array = np.zeros((4,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Arrange functions in numpy
arrange_array = np.arange(1,10, 2) # the first argument will be start which is 1n this case the secound argument is where it will stop the array and the last argument will be the steps it will take
print(arrange_array)

[1 3 5 7 9]


In [ ]:
# Array operation

a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
result = a + b

print(result)

# this is called concatination of arrays by using plus operator as an operator

[ 2  4  6  8 10]


In [ ]:
# Broad casting

a = np.array([[1,2,3,4] , [1,2,3,4]])
b = 10
result = a + b
print(result)

[[11 12 13 14]
 [11 12 13 14]]


In [ ]:
sum_array = np.array([1,2,3,4,5,6,7])

print(sum_array.sum())
print(sum_array.mean())
print(sum_array.max())

# NUMPY dot function will do the dot product for two arrays

first_array = np.array([1,2,3,4,5])
secound_array = np.array([1,2,3,4,5])

third_array = np.dot(first_array , secound_array)

print(third_array)


28
4.0
7
55


In [ ]:
# Array shaping and reshaping in numpy

my_array = np.array([1,2,3,4,5])
my_array.shape


(5,)

In [ ]:
arr = np.arange(1, 10)
reshaped_arr = arr.reshape((3, 3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
