In [1]:
import numpy as np

The Basics
For Dimensions we can use a.ndim
for shape we can use b.shape

In [2]:
#  Get a dimension
b = np.array([1,2,3])
print(b)

[1 2 3]


In [3]:
b.ndim

1

In [4]:
a = np.array([[1,2,3,4,5,6] , [2,3,4,5,5,5]])
print(a)

[[1 2 3 4 5 6]
 [2 3 4 5 5 5]]


In [6]:
a.shape # shape of it will represent how much rows and columns it has
# The first item will be the rows and the secound wil be columns

(2, 6)

In [23]:
practise_array = np.array([[1,2,3,4,5],[1,2,3,4,5]] , dtype='int32')
print(practise_array)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [26]:
practise_array.itemsize # for the total size it will take

4

In [28]:
practise_array.size # this is for the size of the array

10

In [30]:
practise_array.size * practise_array.itemsize # this the total size of the memory it will take

40

In [33]:
practise_array.nbytes # its the same as above

40